# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0575fd87dd83068ea429c4dcd67b828a3593a980c2c373c1d7dfd69eeb824b0bf875659646204d133b33f2615e4cfda7f30c59687cebfd6696b19617ef57118c

test:
  secret_key_base: 2d7fd55cf64e1f42b798ea2a0679f5c5d5d6e69fe62fe6977758525d0461024be4cd08ab3746fc908f3c3323f515b4fcb8fe347ac3c12bd86cc2f50cf6a03984

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
